logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.jdbc: DEBUG

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user1
    password: password1
  flyway:
    enabled: true
    locations: "classpath:db/migration"
    baselineOnMigrate: true
    baselineVersion: 1
  jpa:
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddlAuto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
      temp:
        use_jdbc_metadata_defaults: false
